version: '3.8'
services:
  postgres-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yoyo
      POSTGRES_DB: gofiber
#     networks:
#       - freecodecamp
# networks:
#   freecodecamp: